### ISSUE TITLE
value of getTime() reset every second?

### ISSUE THREAD

**Issue by michaelvogt** [google-ar/sceneform-android-sdk#290]
When adding something like `material.baseColor = vec4(sin(getTime()), 1.0, 0.0, 1.0);` to a custom material fragment shader, it seems like the value getTime() returns starts from 0 every second. Is this expected behaviour? 

It is written in the docs that resets happen, but the way it is right now doesn't allow to use this value for animations () or color fades at all.

**Comment by romainguy** [comment]
The docs were not precise enough. `getTime()` is indeed the current fraction of a second.

**Comment by michaelvogt** [comment]
Where can I then get a continuous time from alternatively, to implement animations like this
[flag](https://www.youtube.com/watch?v=l5dbSS9BcqY)?

**Comment by romainguy** [comment]
`getTime()` should work fine for this, you can simply multiply it by a constant (`* 4.0` for instance) to get longer animation cycles.

**Comment by michaelvogt** [comment]
The question is more like, if the current behaviour is there to stay, or is there a chance to get a longer time span through the `getTime()` call.

**Comment by michaelvogt** [comment]
Understandable. How about an additional call, for example `getContinuousTime()` ;)

**Comment by romainguy** [comment]
We've been talking about it adding something like this yes. But it's not more useful for the case of a flag :)

**Comment by michaelvogt** [comment]
Would be good to get this feature. The flag was just an example.

**Comment by KrzysztofWrobel** [comment]
I'm in a similar situation. Tried to make a deformation shader with `material.worldPosition += vec4(0.1,0,0, 0) * sin(frameUniforms.time * 3.14);` and that's the only way I get a smooth cycle. Now I would like to slow down this deformation effect. :)

**Comment by pixelflinger** [comment]
Note that nothing prevents you to supply your own time as material parameter.

**Comment by romainguy** [comment]
The issue is being fixed in Filament: https://github.com/google/filament/pull/601

Once this gets in, Sceneform will have to integrate.

**Comment by michaelvogt** [comment]
Excellent, thank you.

Is there a way to know which version of fillament is used in a Sceneform version?

**Comment by romainguy** [comment]
We use tags based on Sceneform versions and we create a GitHub release for every code drop for Sceneform. See https://github.com/google/filament/releases (sceneform1.7-pr1 for instance).

**Comment by michaelvogt** [comment]
I see. Was just wondering as I didn't remember seeing this mentioned anywhere on the Sceneform side

**Comment by manugomez95** [comment]
This is still happening on Sceneform 1.11.0

> 
> 
> `getTime()` should work fine for this, you can simply multiply it by a constant (`* 4.0` for instance) to get longer animation cycles.

And this doesn't fix the issue. Time resets each second so thats the maximum duration an animation can have. Multiplying just makes the animation faster or slower but still with the one second constraint.

**Comment by romainguy** [comment]
You should now be able to use:

```
**getUserTime()**                   | float4   |  Current time in seconds: `time`, `(double)time - time`, `0`, `0`
```

Unlike `getTime()`, `getUserTime()` doesn't get reset every second. See https://github.com/google/filament/pull/601 for more details.
